# Generated by Django 2.2.5 on 2021-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolean_expression',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
